component: http
name: http-express-U_av0yRdN
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    framework: express
    name: '${name}'
    runtime: Nodejs12.16
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    layers:
      - name: '${output:${stage}:${app}:blogserver-layer.name}'
        version: '${output:${stage}:${app}:blogserver-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains:
      - domain: app.yihuiblog.top
        certId: p3I1wkb6
        protocols:
          - https
        pathMap:
          - path: /
            environment: release
        isDefaultMapping: false
  region: ap-guangzhou
  isAutoCiDeploy: false
  static: {}
org: '1259409954'
app: blogserver
stage: dev
